export const STUDENTS_LOAD_REQUEST = 'STUDENTS_LOAD_REQUEST';
export const STUDENTS_LOAD_SUCCESS = 'STUDENTS_LOAD_SUCCESS';
export const STUDENTS_LOAD_FAILURE = 'STUDENTS_LOAD_FAILURE';

export const STUDENT_LOAD_REQUEST = 'STUDENT_LOAD_REQUEST';
export const STUDENT_LOAD_SUCCESS = 'STUDENT_LOAD_SUCCESS';
export const STUDENT_LOAD_FAILURE = 'STUDENT_LOAD_FAILURE';
